name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.2', '7.3', '7.4']

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        extension-csv: dom
        coverage: xdebug
    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --ignore-platform-reqs
    - name: PHP Code Sniffer
      if: matrix.php-versions == '7.2'
      run: vendor/bin/phpcs --report=full --extensions=php -p --standard=PSR2 ./src ./tests
    - name: PHP Mess Detector
      if: matrix.php-versions == '7.2'
      run: vendor/bin/phpmd ./src text cleancode,codesize,controversial,design,naming,unusedcode
    - name: PHP Unit Tests with coverage
      if: matrix.php-versions == '7.4'
      run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - name: PHP Unit Tests
      if: matrix.php-versions != '7.4'
      run: vendor/bin/phpunit
    - name: Send to coveralls
      if: matrix.php-versions == '7.2'
      run: php vendor/bin/php-coveralls -v
      env:
        COVERALLS_RUN_LOCALLY: 1
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
